//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Seanslar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seanslar()
        {
            this.Musteriler = new ObservableCollection<Musteriler>();
        }
    
        public int SeansID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public System.DateTime FilmSaati { get; set; }
        public Nullable<int> SalonID { get; set; }
        public Nullable<int> Renk { get; set; }
    
        public virtual Filmler Filmler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Musteriler> Musteriler { get; set; }
        public virtual Salonlar Salonlar { get; set; }
    }
}
