//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Siparisler
    {
        public int SiparisID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<double> SiparisAdet { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<double> SiparisBirimFiyat { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
