//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tahsilatlar
    {
        public int TahsilatID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<System.DateTime> TahsilatTarihi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
